# Generated by Django 5.2.6 on 2025-09-27 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day number of the construction project', validators=[django.core.validators.MinValueValidator(1)])),
                ('active_crews', models.IntegerField(help_text='Number of active crews working on this day', validators=[django.core.validators.MinValueValidator(1)])),
                ('ice_amount', models.IntegerField(help_text='Amount of work completed', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.IntegerField(help_text="Cost for this day's work", validators=[django.core.validators.MinValueValidator(0)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='thewall.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='thewall.profile')),
            ],
        ),
    ]
