# Generated by Django 5.2.6 on 2025-09-27 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='active_crews',
            field=models.IntegerField(help_text='Number of active crews working on this day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='ice_amount',
            field=models.IntegerField(help_text='Amount of ice/work completed in cubic yards', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='thewall.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('profile', 'day')},
        ),
        migrations.AlterModelTable(
            name='dailyprogress',
            table='daily_progress',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
        migrations.AlterModelTable(
            name='section',
            table='sections',
        ),
    ]
